FROM graylog/graylog:3.1

COPY graylog/graylog-plugin-slack-notification-3.1.1.jar /usr/share/graylog/plugin/
COPY graylog/metrics-reporter-prometheus-3.0.0.jar /usr/share/graylog/plugin/
COPY graylog/graylog-plugin-redis-0.1.1.jar /usr/share/graylog/plugin/
